apiVersion: v1
kind: Pod
metadata:
  name: utils
  labels:
    name: utils
spec:
  containers:
  - name: utils
    image: groksrc/utils
    imagePullPolicy: Always
    tty: true
    stdin: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
